#!/bin/sh

set -eu

Homedir="$(d=${0%/*}/; [ "_$d" = "_$0/" ] && d='./'; cd "$d.."; pwd)"
cd "$Homedir"
for file in $(find './lib/utils' -not -type d); do
    . "$file"
done

subcmd="$1" && shift

#@ SUBCMD_CASE
case "$subcmd" in
    list-installed) # `snap list`
        debug snap list
        ;;
    search)         # `snap find [args...]`
        debug snap find "$@"
        ;;
    update)         # `snap refresh --list`
        debug snap refresh --list
        ;;
    upgrade)        # `sudo snap refresh`
        debug sudo snap refresh
        ;;
esac
