#!/bin/sh

######################################################################
# Initial Configuration
######################################################################

# === Initialize shell environment ===================================
set -u
umask 0022
export LC_ALL=C
export UNIX_STD=2003

# === Define the functions for printing usage and exiting ============
print_usage_and_exit () {
  cat <<-USAGE 1>&2
	Usage   : ${0##*/} [-pm <package-manager>] <subcommand> <options>
	Subcommands : install, search, update, upgrade
	USAGE
  exit 1
}
error_exit() {
  ${2+:} false && echo "${0##*/}: $2" 1>&2
  exit $1
}
print_and_exec () {
  echo "${PS4}${*}" 1>&2
  "${@}"
}

# === Detect home directory of this app ==============================
Homedir="$(d=${0%/*}/; [ "_$d" = "_$0/" ] && d='./'; cd "$d."; pwd)"


######################################################################
# Argument Parsing
######################################################################

# === Initialize parameters ==========================================
prefix='pmo-'

# === Read options ===================================================
while :; do
  case "${1:-}" in
    --pm=*)
        pm=$(printf '%s' "${1#--pm=}" | tr -d '\n')
        shift
        ;;
    --prefix=*)
        prefix=$(printf '%s' "${1#--prefix=}" | tr -d '\n')
        shift
        ;;
    --|-)
        break
        ;;
    --*|-*)
        error_exit 1 'Invalid option'
        ;;
    *)
        break
        ;;
  esac
done

# === Read Subcommand ================================================
subcmd="${1:-}"
shift

# === Validate file argument and generate an argument for MIME making command
case "${subcmd}" in
    install|search|update|upgrade) ;;
    *) print_usage_and_exit ;;
esac


######################################################################
# Main Routine
######################################################################

export PS4='==> '

if [ "${subcmd}" = install ] || [ -n "${pm:-}" ]; then
    (set -x; "${pm}" "${subcmd}" "${@}")
    return
fi

pms=$(printf '%s\n' "${PATH}" |
          tr ':' '\n' |
          while IFS= read p; do [ -d "${p}" ] && find "${p}" -maxdepth 1; done |
          grep "/${prefix}[^/]*\$" |
          rev | sort | rev |
          awk '{file=$0; gsub(/.*\//,"",file); if(pre!=file)print; pre=file}' |
          tr '\n' ':' | sed 's/:$//')

printf '%s\n' "${pms}" |
    tr ':' '\n' |
    while IFS= read pm; do
        export PS4='==> '
        sudo=''
        case "${pm##*/}" in
            apt|"${prefix}apt") sudo='sudo' ;;
        esac
        case "${subcmd}" in
             search) sudo='' ;;
        esac
        print_and_exec ${sudo} "${pm}" "${subcmd}" "${@}" </dev/tty
    done
