#!/bin/sh

######################################################################
# Initial Configuration
######################################################################

# === Initialize shell environment ===================================
set -u
umask 0022
export LC_ALL=C
export UNIX_STD=2003

# === Define the functions for printing usage and exiting ============
print_usage_and_exit () {
  cat <<-USAGE 1>&2
	Usage   : ${0##*/}
	USAGE
  exit 1
}
error_exit() {
  ${2+:} false && echo "${0##*/}: $2" 1>&2
  exit $1
}

# === Detect home directory of this app ==============================
Homedir="$(d=${0%/*}/; [ "_$d" = "_$0/" ] && d='./'; cd "$d."; pwd)"


######################################################################
# Argument Parsing
######################################################################

# === Read options ===================================================
while :; do
  case "${1:-}" in
    --pm=*)
        pm=$(printf '%s' "${1#--pm=}" | tr -d '\n')
        shift
        ;;
    --|-)
        break
        ;;
    --*|-*)
        error_exit 1 'Invalid option'
        ;;
    *)
        break
        ;;
  esac
done

# === Read Subcommand ================================================
subcmd="${1:-}"

# === Validate file argument and generate an argument for MIME making command
case "${subcmd}" in
    search|update|upgrade)
        shift
        ;;
    *) print_usage_and_exit ;;
esac


######################################################################
# Main Routine
######################################################################

if [ -n "${pm:-}" ]; then
    "pmo-${pm}" "${subcmd}" "${@}"
    return
fi

cat <<-EOF |
	apt
	brew
	EOF
    while read pm; do
        export PS4='==> '
        sudo=''
        case "${pm##*/}" in
            apt) sudo='sudo' ;;
        esac
        (set -x; $sudo "${pm}" "${subcmd}" "${@}" </dev/tty)
    done
