#!/bin/sh

######################################################################
# Initial Configuration
######################################################################

# === Initialize shell environment ===================================
set -eu
umask 0022
export LC_ALL=C
export UNIX_STD=2003

# === Define the functions for printing usage and exiting ============
print_usage_and_exit() {
    cat <<-USAGE 1>&2
	Usage   : ${0##*/} [<options>] <subcommand> <pm-options>
	Optoins : --pm=<package-manager>
	Subcommands : install, search, update, upgrade
	USAGE
    exit 1
}

error_exit() {
    ${2+:} false && echo "${0##*/}: $2" 1>&2
    exit $1
}

print_and_exec() (
    PS4=$( (set -x; :) 2>&1 | sed 's/:$//')
    echo "${PS4}${*}" 1>&2
    PS4=$(printf '%s' "${PS4}" | sed 's/\(.\) $/\1\0/')
    PS4="${PS4}" "$@"
)

# === Detect home directory of this app ==============================
Homedir="$(d=${0%/*}/; [ "_$d" = "_$0/" ] && d='./'; cd "$d."; pwd)"


######################################################################
# Argument Parsing
######################################################################

# === Read options ===================================================
while :; do
    case "${1:-}" in
        --pm=*)
            pm=$(printf '%s' "${1#--pm=}" | tr -d '\n')
            shift
            ;;
        --)
            shift
            break
            ;;
        --help|-h|--version)
            print_usage_and_exit
            ;;
        --*|-*)
            error_exit 1 'Invalid option'
            ;;
        *)
            break
            ;;
    esac
done

# === Read Subcommand ================================================
subcmd="${1:-}"
shift


######################################################################
# Main Routine
######################################################################

if [ "${subcmd}" = install ] || [ -n "${pm:-}" ]; then
    print_and_exec "${Homedir}/bin/${pm}" "${subcmd}" "$@"
    exit
fi

pms=$(find "${Homedir}/bin" -not -type d -not -path '*/.*' | tr '\n' ':' | sed 's/:$//')

code=0
i=0
l=$(printf '%s\n' "${pms}" | tr ':' '\n' | wc -l)
while [ "${i}" -lt "${l}" ]; do
    pm=$(printf '%s\n' "${pms}" | tr ':' '\n' | sed -n "$((i+1))p")
    if ! print_and_exec "${pm}" "${subcmd}" "$@" </dev/tty; then
        code=1
    fi
    i=$((i+1))
done

exit "${code}"
