#!/bin/sh

set -eu

Homedir="$(d=${0%/*}/; [ "_$d" = "_$0/" ] && d='./'; cd "$d."; pwd)"
for file in $(find "${Homedir}/../lib" -not -type d); do
    . "$file"
done

subcmd="$1" && shift

#@ SUBCMD_CASE
case "$subcmd" in
    list-installed) # `asdf list`
        asdf list
        ;;
    update)         # `asdf plugin update --all`
        asdf plugin update --all
        ;;
    upgrade)        # install and set the latest version of all plugins
        asdf current 2>/dev/null | cut -d ' ' -f 1 | while read line; do
            debug asdf install "$line" latest
            debug asdf global "$line" latest
        done
        ;;
esac
