#!/bin/sh
# -*- mode: shell-script -*-

set -eu

Homedir="$(d=${0%/*}/; [ "_$d" = "_$0/" ] && d='./'; cd "$d."; pwd)"
for file in $(find "${Homedir}/../lib" -not -type d); do
    . "$file"
done

subcmd="$1" && shift

#@ SUBCMD_CASE
case "$subcmd" in
    list-installed) # `brew list`
        debug brew list
        ;;
    search)         # `brew search [args...]`
        debug brew search "$@"
        ;;
    update)         # `brew update`
        debug brew update
        ;;
    upgrade)        # `brew upgrade [args...]`
        debug brew upgrade "$@"
        ;;
esac
