#!/bin/sh
# -*- mode: shell-script -*-

set -eu

debug() (
    (PS4=':'; set -x; : "${@}")
    "$@"
)

#@ SUBCMD_CASE
case "${subcmd}" in
    list)            # `apt list`
        debug apt list
        ;;
    list-installed)  # `apt list --installed`
        debug apt list --installed
        ;;
    list-upgradable) # `apt list --upgradable`
        debug apt list --upgradable
        ;;
    search)          # `sudo apt search [args...]`
        debug sudo apt search "$@"
        ;;
    update)          # `sudo apt update`
        debug sudo apt update
        ;;
    upgrade)         # `sudo apt upgrade [args...]`
        debug sudo apt upgrade "$@"
        ;;
esac
