#!/bin/sh

set -eu

Homedir="$(d=${0%/*}/; [ "_$d" = "_$0/" ] && d='./'; cd "$d../.."; pwd)"
cd "$Homedir"
for file in $(find './utils' -not -type d); do
    . "$file"
done

subcmd="$1" && shift

#@ SUBCMD_CASE
case "$subcmd" in
    install)        # `asdf plugin add <plugin> [<git-url>]`
        debug asdf plugin add "$@"
        debug asdf install "$1" latest
        debug asdf global "$1" latest
        ;;
    remove)         # `asdf plugin remove <plugin>`
        debug asdf plugin remove "$1"
        ;;
    list-installed) # `asdf list`
        debug asdf list
        ;;
    update)         # `asdf plugin update --all`
        debug asdf plugin update --all
        ;;
    upgrade)        # install and set the latest version of all plugins
        asdf current 2>/dev/null | cut -d ' ' -f 1 | while read line; do
            debug asdf install "$line" latest
            debug asdf global "$line" latest
        done
        ;;
esac
