#!/bin/sh

set -eu

Homedir="$(d=${0%/*}/; [ "_$d" = "_$0/" ] && d='./'; cd "$d../.."; pwd)"
cd "$Homedir"
for file in $(find './utils' -not -type d); do
    . "$file"
done

subcmd="$1" && shift

#@ SUBCMD_CASE
case "$subcmd" in
    install)        # `cargo instal [args...]`
        debug cargo install "$@"
        ;;
    remove)         # `cargo uninstall [args...]`
        debug cargo uninstall "$@"
        ;;
    list-installed) # `cargo install --list`
        debug cargo install --list
        ;;
    search)         # `cargo search [args...]`
        debug cargo search "$@"
        ;;
    upgrade)        # upgrade installed packages
        if cargo install-update --version >/dev/null 2>&1; then
            if [ $# -eq 0 ]; then
                debug cargo install-update --all
            else
                debug cargo install-update "$@"
            fi
            exit
        fi

        cargo install --list | grep '^[^ ]' | sed 's/:$//' | while read -r line; do
            installed=${line##* v}
            latest=$(cargo info "${line%% *}" 2>/dev/null | sed -n 's/^version: //p')
            if ! [ "$installed" = "$latest" ]; then
                debug cargo install "${line%% *}" --force
            fi
        done
        ;;
esac
