#!/bin/sh

set -eu

Homedir="$(d=${0%/*}/; [ "_$d" = "_$0/" ] && d='./'; cd "$d../.."; pwd)"
cd "$Homedir"
for file in $(find './utils' -not -type d); do
    . "$file"
done

subcmd="$1" && shift

#@ SUBCMD_CASE
case "$subcmd" in
    list-installed) # `kubectl krew list`
        debug kubectl krew list
        ;;
    search)         # `kubectl krew search`
        debug kubectl krew search "$@"
        ;;
    update)         # `kubectl krew update`
        debug kubectl krew update
        ;;
    upgrade)        # `kubectl krew upgrade`
        debug kubectl krew upgrade "$@"
        ;;
esac
